version: '3'
services:
  db:
    image:  postgres:14.11
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      POSTGRES_USER: werewolf
      POSTGRES_PASSWORD: password
    healthcheck:
      test: pg_isready -U "${POSTGRES_USER:-postgres}" || exit 1
