version: '3'

tasks:
  clean:
    cmds:
      - rm -rf ./werewolf-cli/pkg/grpc/*
      - mkdir -p ./werewolf-cli/pkg/grpc
      - rm -rf ./backend-kotlin/src/generated/
      - mkdir -p ./backend-kotlin/src/generated/java
      - mkdir -p ./backend-kotlin/src/generated/kotlin
  gen-grpc-client: 
    cmds:
      - protoc --go_out=./werewolf-cli/pkg/grpc/ --go-grpc_out=./werewolf-cli/pkg/grpc/ proto/village.proto
  gen-grpc-server:
    cmds:
      - protoc --java_out=./backend-kotlin/src/generated/java --grpc-java_out=./backend-kotlin/src/generated/java proto/village.proto
  gen-grpc:
    cmds:
      - task: clean
      - task: gen-grpc-client
      - task: gen-grpc-server
  gen-sqlc:
    dir: ./backend-kotlin
    cmds:
      - sqlc generate
  generate:
    cmds:
      - task: clean
      - task: gen-grpc
      - task: gen-sqlc


