// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/game.proto

package game

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GameService_GetActor_FullMethodName          = "/game.GameService/GetActor"
	GameService_GetGameStatus_FullMethodName     = "/game.GameService/GetGameStatus"
	GameService_GetDeadPlayersLog_FullMethodName = "/game.GameService/GetDeadPlayersLog"
	GameService_GetSelfActionLog_FullMethodName  = "/game.GameService/GetSelfActionLog"
	GameService_ExecSelfAction_FullMethodName    = "/game.GameService/ExecSelfAction"
	GameService_GetGameResult_FullMethodName     = "/game.GameService/GetGameResult"
)

// GameServiceClient is the client API for GameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GameService 定義
type GameServiceClient interface {
	GetActor(ctx context.Context, in *GetActorRequest, opts ...grpc.CallOption) (*GetActorResponse, error)
	GetGameStatus(ctx context.Context, in *GetGameStatusRequest, opts ...grpc.CallOption) (*GetGameStatusResponse, error)
	GetDeadPlayersLog(ctx context.Context, in *GetDeadPlayersLogRequest, opts ...grpc.CallOption) (*GetDeadPlayersLogResponse, error)
	GetSelfActionLog(ctx context.Context, in *GetSelfActionLogRequest, opts ...grpc.CallOption) (*GetSelfActionLogResponse, error)
	ExecSelfAction(ctx context.Context, in *ExecSelfActionRequest, opts ...grpc.CallOption) (*ExecSelfActionResponse, error)
	GetGameResult(ctx context.Context, in *GetGameResultRequest, opts ...grpc.CallOption) (*GetGameResultResponse, error)
}

type gameServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameServiceClient(cc grpc.ClientConnInterface) GameServiceClient {
	return &gameServiceClient{cc}
}

func (c *gameServiceClient) GetActor(ctx context.Context, in *GetActorRequest, opts ...grpc.CallOption) (*GetActorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetActorResponse)
	err := c.cc.Invoke(ctx, GameService_GetActor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetGameStatus(ctx context.Context, in *GetGameStatusRequest, opts ...grpc.CallOption) (*GetGameStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGameStatusResponse)
	err := c.cc.Invoke(ctx, GameService_GetGameStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetDeadPlayersLog(ctx context.Context, in *GetDeadPlayersLogRequest, opts ...grpc.CallOption) (*GetDeadPlayersLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeadPlayersLogResponse)
	err := c.cc.Invoke(ctx, GameService_GetDeadPlayersLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetSelfActionLog(ctx context.Context, in *GetSelfActionLogRequest, opts ...grpc.CallOption) (*GetSelfActionLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSelfActionLogResponse)
	err := c.cc.Invoke(ctx, GameService_GetSelfActionLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) ExecSelfAction(ctx context.Context, in *ExecSelfActionRequest, opts ...grpc.CallOption) (*ExecSelfActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecSelfActionResponse)
	err := c.cc.Invoke(ctx, GameService_ExecSelfAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetGameResult(ctx context.Context, in *GetGameResultRequest, opts ...grpc.CallOption) (*GetGameResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGameResultResponse)
	err := c.cc.Invoke(ctx, GameService_GetGameResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameServiceServer is the server API for GameService service.
// All implementations must embed UnimplementedGameServiceServer
// for forward compatibility.
//
// GameService 定義
type GameServiceServer interface {
	GetActor(context.Context, *GetActorRequest) (*GetActorResponse, error)
	GetGameStatus(context.Context, *GetGameStatusRequest) (*GetGameStatusResponse, error)
	GetDeadPlayersLog(context.Context, *GetDeadPlayersLogRequest) (*GetDeadPlayersLogResponse, error)
	GetSelfActionLog(context.Context, *GetSelfActionLogRequest) (*GetSelfActionLogResponse, error)
	ExecSelfAction(context.Context, *ExecSelfActionRequest) (*ExecSelfActionResponse, error)
	GetGameResult(context.Context, *GetGameResultRequest) (*GetGameResultResponse, error)
	mustEmbedUnimplementedGameServiceServer()
}

// UnimplementedGameServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameServiceServer struct{}

func (UnimplementedGameServiceServer) GetActor(context.Context, *GetActorRequest) (*GetActorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActor not implemented")
}
func (UnimplementedGameServiceServer) GetGameStatus(context.Context, *GetGameStatusRequest) (*GetGameStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGameStatus not implemented")
}
func (UnimplementedGameServiceServer) GetDeadPlayersLog(context.Context, *GetDeadPlayersLogRequest) (*GetDeadPlayersLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeadPlayersLog not implemented")
}
func (UnimplementedGameServiceServer) GetSelfActionLog(context.Context, *GetSelfActionLogRequest) (*GetSelfActionLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSelfActionLog not implemented")
}
func (UnimplementedGameServiceServer) ExecSelfAction(context.Context, *ExecSelfActionRequest) (*ExecSelfActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecSelfAction not implemented")
}
func (UnimplementedGameServiceServer) GetGameResult(context.Context, *GetGameResultRequest) (*GetGameResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGameResult not implemented")
}
func (UnimplementedGameServiceServer) mustEmbedUnimplementedGameServiceServer() {}
func (UnimplementedGameServiceServer) testEmbeddedByValue()                     {}

// UnsafeGameServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameServiceServer will
// result in compilation errors.
type UnsafeGameServiceServer interface {
	mustEmbedUnimplementedGameServiceServer()
}

func RegisterGameServiceServer(s grpc.ServiceRegistrar, srv GameServiceServer) {
	// If the following call pancis, it indicates UnimplementedGameServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameService_ServiceDesc, srv)
}

func _GameService_GetActor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetActor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_GetActor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetActor(ctx, req.(*GetActorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetGameStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetGameStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_GetGameStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetGameStatus(ctx, req.(*GetGameStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetDeadPlayersLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeadPlayersLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetDeadPlayersLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_GetDeadPlayersLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetDeadPlayersLog(ctx, req.(*GetDeadPlayersLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetSelfActionLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSelfActionLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetSelfActionLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_GetSelfActionLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetSelfActionLog(ctx, req.(*GetSelfActionLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_ExecSelfAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecSelfActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).ExecSelfAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_ExecSelfAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).ExecSelfAction(ctx, req.(*ExecSelfActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetGameResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetGameResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_GetGameResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetGameResult(ctx, req.(*GetGameResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GameService_ServiceDesc is the grpc.ServiceDesc for GameService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "game.GameService",
	HandlerType: (*GameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetActor",
			Handler:    _GameService_GetActor_Handler,
		},
		{
			MethodName: "GetGameStatus",
			Handler:    _GameService_GetGameStatus_Handler,
		},
		{
			MethodName: "GetDeadPlayersLog",
			Handler:    _GameService_GetDeadPlayersLog_Handler,
		},
		{
			MethodName: "GetSelfActionLog",
			Handler:    _GameService_GetSelfActionLog_Handler,
		},
		{
			MethodName: "ExecSelfAction",
			Handler:    _GameService_ExecSelfAction_Handler,
		},
		{
			MethodName: "GetGameResult",
			Handler:    _GameService_GetGameResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/game.proto",
}
